const parkAreas = [
  {
    name: "Lakefront Park",
    area_id: 1,
    place: "Riverside",
    no_free_slots: 47,
    distance: "500.83",
    coords: {latitude: 9.1257316, longitude: 76.9038329},
    average_rating: "2.7",
    price_per_hr: 10,
    total_reviews: 11,
    exclusive_features: [
      "Free Wifi",
      "Free Parking with fee *_*",
      "Free Water",
      "Free Food",
      "Charging Stations",
      "Secure Parking",
    ],
  },
  {
    name: "City Park",
    area_id: 2,
    place: "Mountain Ridge",
    no_free_slots: 3,
    distance: "4.17",
    coords: {latitude: 9.222033, longitude: 76.744302},
    average_rating: "1.1",
    price_per_hr: 35,
    total_reviews: 2,
    exclusive_features: [
      "Free Wifi",
      "Free Water",
      "Free Food",
      "Charging Stations",
      "Secure Parking",
    ],
  },
  {
    name: "Green Haven",
    area_id: 3,
    place: "City Center",
    no_free_slots: 24,
    distance: "6.54",
    coords: {latitude: 9.203298, longitude: 76.754382},
    average_rating: "4.2",
    price_per_hr: 20,
    total_reviews: 5,
    exclusive_features: [
      "Free Wifi",
      "Free Water",
      "Free Food",
      "Charging Stations",
      "Secure Parking",
    ],
  },
  {
    name: "Botanical Gardens",
    area_id: 4,
    place: "Mountain Ridge",
    no_free_slots: 9,
    distance: "18.38",
    coords: {latitude: 8.434534, longitude: 77.031217},
    average_rating: "2.8",
    price_per_hr: 9,
    total_reviews: 13,
    exclusive_features: [
      "Free Wifi",
      "Free Water",
      "Charging Stations",
      "Secure Parking",
    ],
  },
  {
    name: "Sunset Valley",
    area_id: 5,
    place: "Suburb",
    no_free_slots: 17,
    distance: "9.09",
    coords: {latitude: 8.50073, longitude: 77.0813},
    average_rating: "4.8",
    price_per_hr: 17,
    total_reviews: 7,
    exclusive_features: [
      "Free Wifi",
      "Free Water",
      "Free Food",
      "Charging Stations",
      "Secure Parking",
    ],
  },
  {
    name: "Urban Oasis",
    area_id: 6,
    place: "Riverside",
    no_free_slots: 29,
    distance: "13.03",
    coords: {latitude: 8.54505, longitude: 76.904207},
    average_rating: "4.9",
    price_per_hr: 30,
    total_reviews: 9,
    exclusive_features: [
      "Free Wifi",
      "Free Water",
      "Free Food",
      "Charging Stations",
      "Secure Parking",
    ],
  },
  {
    name: "Urban Oasis",
    area_id: 7,
    place: "Downtown",
    no_free_slots: 20,
    distance: "15.41",
    coords: {latitude: 8.544838, longitude: 76.903519},
    average_rating: "4.2",
    price_per_hr: 40,
    total_reviews: 3,
    exclusive_features: [
      "Free Wifi",
      "Free Water",
      "Free Food",
      "Charging Stations",
      "Secure Parking",
    ],
  },
  {
    name: "Meadow Park",
    area_id: 8,
    place: "Downtown",
    no_free_slots: 11,
    distance: "5.62",
    coords: {latitude: 8.546529, longitude: 76.903799},
    average_rating: "3.9",
    price_per_hr: 17,
    total_reviews: 4,
    exclusive_features: [
      "Free Wifi",
      "Free Water",
      "Free Food",
      "Charging Stations",
      "Secure Parking",
    ],
  },
  {
    name: "Pine Grove",
    area_id: 9,
    place: "Mountain Ridge",
    no_free_slots: 42,
    distance: "6.33",
    coords: {latitude: 8.544326, longitude: 76.907457},
    average_rating: "3.3",
    price_per_hr: 10,
    total_reviews: 6,
    exclusive_features: [
      "Free Wifi",
      "Free Water",
      "Free Food",
      "Charging Stations",
      "Secure Parking",
    ],
  },
  {
    name: "Botanical Gardens",
    area_id: 10,
    place: "Suburb",
    no_free_slots: 22,
    distance: "16.96",
    coords: {latitude: 8.541787, longitude: 76.907146},
    average_rating: "3.2",
    price_per_hr: 15,
    total_reviews: 8,
    exclusive_features: [
      "Free Wifi",
      "Free Water",
      "Free Food",
      "Charging Stations",
      "Secure Parking",
    ],
  },

  //
  //
  {
    name: "Sunset Valley",
    area_id: 11,
    place: "City Center",
    no_free_slots: 14,
    distance: "8.63",
    coords: {latitude: 8.750789, longitude: 76.935431},
    average_rating: "4.3",
    price_per_hr: 15,
    total_reviews: 8,
    exclusive_features: [
      "Free Wifi",
      "Free Water",
      "Free Food",
      "Charging Stations",
      "Secure Parking",
    ],
  },
  {
    name: "Urban Oasis",
    area_id: 12,
    place: "City Center",
    no_free_slots: 19,
    distance: "9.02",
    coords: {latitude: 8.7504607, longitude: 76.9356233},
    average_rating: "4.9",
    price_per_hr: 30,
    total_reviews: 9,
    exclusive_features: [
      "Free Wifi",
      "Free Water",
      "Free Food",
      "Charging Stations",
      "Secure Parking",
    ],
  },
  {
    name: "Cities Oasis",
    area_id: 13,
    place: "City Center",
    no_free_slots: 15,
    distance: "9.05",
    coords: {latitude: 8.7524607, longitude: 76.9352233},
    average_rating: "4.2",
    price_per_hr: 40,
    total_reviews: 3,
    exclusive_features: [
      "Free Wifi",
      "Free Water",
      "Free Food",
      "Charging Stations",
      "Secure Parking",
    ],
  },
  {
    name: "Cities Oasis",
    area_id: 14,
    place: "City Center",
    no_free_slots: 10,
    distance: "9.05",
    coords: {latitude: 8.749657, longitude: 76.932485},
    average_rating: "4.2",
    price_per_hr: 40,
    total_reviews: 3,
    exclusive_features: [
      "Free Wifi",
      "Free Water",
      "Free Food",
      "Charging Stations",
      "Secure Parking",
    ],
  },
  {
    name: "Cities Oasis",
    area_id: 15,
    place: "City Center",
    no_free_slots: 10,
    distance: "9.05",
    coords: {latitude: 8.75025, longitude: 76.937773},
    average_rating: "4.2",
    price_per_hr: 40,
    total_reviews: 3,
    exclusive_features: [
      "Free Wifi",
      "Free Water",
      "Free Food",
      "Charging Stations",
      "Secure Parking",
    ],
  },
  {
    name: "Cities Oasis",
    area_id: 16,
    place: "City Center",
    no_free_slots: 10,
    distance: "9.05",
    coords: {latitude: 8.750203, longitude: 76.933984},
    average_rating: "4.2",
    price_per_hr: 40,
    total_reviews: 3,
    exclusive_features: [
      "Free Wifi",
      "Free Water",
      "Free Food",
      "Charging Stations",
      "Secure Parking",
    ],
  },
];

export default parkAreas;
